apiVersion: v1
kind: Pod
metadata:
  labels:
    run: reactle
  name: reactle
  namespace: default
spec:
  containers:
  - image: ghcr.io/cprivitere/react-wordle:latest
    name: reactle
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: reactle
  name: reactle
  namespace: default
spec:
  ports:
  - nodePort: 31000
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: reactle
  type: NodePort
